version: '2'

services:
    php:
        image: php:7.1-cli
        volumes:
            - ./:/php/
        working_dir: /php/
        ports:
            - "8888:8888"

    composer:
        image: composer/composer
        volumes:
            - ./:/composer/
        working_dir: /composer/

    phpunit:
        image: phpunit/phpunit
        volumes:
            - ./:/phpunit/
        working_dir: /phpunit/
